# Generated by Django 2.1.4 on 2018-12-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cham',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='disable_communication',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='fx_rate',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='k_id',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='launched_at',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='location',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='pledged',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='spotlight',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='staff_pick',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='state',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='state_changed_at',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='static_usd_rate',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='urls',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='usd_pledged',
        ),
        migrations.RemoveField(
            model_name='cham',
            name='usd_type',
        ),
    ]
